### ISSUE TITLE
how to generate drug or protein embeddings

### ISSUE THREAD

**Issue by cynricfu** [kexinhuang12345/DeepPurpose#34] opened 2020-10-28 01:12 UTC
Hi, I am working on a related project and trying to use DeepPurpose to generate drug and protein embeddings for other downstream tasks.
I would like to ask is there a function/method in DeepPurpose to generate representation vectors given a list of drugs or proteins, instead of directly predicting an affinity score.

**Comment by kexinhuang12345** [comment] 2020-10-28 03:31
Hi, there is no provided API for that, but it should be easy if you look at the encoders.py file, and each encoder could take in A['drug_encoding'] where A is the data output from utils.data_process function.

**Comment by cynricfu** [comment] 2020-10-28 07:24
The code assumes the DTI setting, where the input is drug-target pairs. But what I want to do is generate embeddings only for a list of drugs, without providing another list of targets. Also, it seems that the output from the data_process function needs to be further processed by data_process_loader.
Anyway, it might require some very deep hacks for me to achieve my goal. I just wonder if this functionality can be supported officially by DeepPurpose, since it is also quite a common use case of a deep learning model.

**Comment by kexinhuang12345** [comment] 2020-10-28 20:52
Thanks for the suggestion, I just made a commit, and now you can use ``utils.obtain_compound_embedding(net, file)`` or ``utils.obtain_protein_embedding(net, file)`` to obtain the embeddings. net is from the standard process to define a DTI model, or DDI, PPI, CompoundPred, ProteinPred model. file is the output of data_process function, for example, to get embeddings for training set in case study 1(a), simply call ``utils.obtain_compound_embedding(net, train)``. The embeddings are also trainable, so you can attach to other model components. 

Let me know if this works for you, i have tested it for a couple of fingerprints and work for me.

**Comment by kexinhuang12345** [comment] 2020-10-29 18:51
closing for now, plz reopen if you have more questions

**Comment by cynricfu** [comment] 2020-11-02 18:01
I use the following lines of code to obtain the dataframe for a list of drugs. Here `drug_l` is an array of smiles strings, `y_l` is a dummy list for compatibility. For models, I use the pretrained DTI models.
```python
X_drug = data_process(X_drug=drug_l, y=y_l,
                      drug_encoding=drug_encoding, target_encoding=target_encoding,
                      split_method='no_split')
```


1. The folder inside `model_cnn_cnn_davis.zip` is named as `model_DeepDTA_DAVIS`, which caused an error.
2. `utils.obtain_compound_embedding` will raise the following error by using the pretrained models which use CNN for drugs:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-9-8a74a03484d4> in <module>()
      1 with torch.no_grad():
----> 2     embs = utils.obtain_compound_embedding(net, X_drug)

D:\mydir\GitHub\DeepPurpose\DeepPurpose\utils.py in obtain_compound_embedding(net, file, file_type)
    956         raise AttributeError
    957 
--> 958     return net.model_drug(torch.FloatTensor(x))
    959 
    960 

TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.
```

3. `utils.obtain_compound_embedding` will raise the following error by using the pretrained models which use MPNN for drugs:
```
ValueError                                Traceback (most recent call last)
<ipython-input-22-8a74a03484d4> in <module>()
      1 with torch.no_grad():
----> 2     embs = utils.obtain_compound_embedding(net, X_drug)

D:\mydir\GitHub\DeepPurpose\DeepPurpose\utils.py in obtain_compound_embedding(net, file, file_type)
    950 def obtain_compound_embedding(net, file, file_type = 'df'):
    951     if file_type == 'df':
--> 952         x = np.stack(file['drug_encoding'].values)
    953     elif file_type == 'array':
    954         x = file

<__array_function__ internals> in stack(*args, **kwargs)

C:\Users\a4542\anaconda3\envs\DeepPurpose\lib\site-packages\numpy\core\shape_base.py in stack(arrays, axis, out)
    419         _arrays_for_stack_dispatcher(arrays, stacklevel=2)
    420 
--> 421     arrays = [asanyarray(arr) for arr in arrays]
    422     if not arrays:
    423         raise ValueError('need at least one array to stack')

C:\Users\a4542\anaconda3\envs\DeepPurpose\lib\site-packages\numpy\core\shape_base.py in <listcomp>(.0)
    419         _arrays_for_stack_dispatcher(arrays, stacklevel=2)
    420 
--> 421     arrays = [asanyarray(arr) for arr in arrays]
    422     if not arrays:
    423         raise ValueError('need at least one array to stack')

C:\Users\a4542\anaconda3\envs\DeepPurpose\lib\site-packages\numpy\core\_asarray.py in asanyarray(a, dtype, order)
    134 
    135     """
--> 136     return array(a, dtype, copy=False, order=order, subok=True)
    137 
    138 

ValueError: only one element tensors can be converted to Python scalars
```

4. When I use Transformer_CNN_BindingDB, `utils.obtain_compound_embedding` only returns a tensor of shape (2, 128)

The pretrained moels using Morgan or Daylight for drugs work fine. But I did not try protein embedding.

**Comment by kexinhuang12345** [comment] 2020-11-02 18:05
did you change the drug_encoding variable in the data_process function for each model? if you can, please include the entire script for reproducibility

**Comment by cynricfu** [comment] 2020-11-02 18:30
The script I use for testing is as follows. The `drugbank_smiles.txt` file is obtained from [https://github.com/gnn4dr/DRKG/blob/master/drugbank_info/drugbank_smiles.txt](https://github.com/gnn4dr/DRKG/blob/master/drugbank_info/drugbank_smiles.txt), which is a list of drug SMILES obtained from drugbank.

```python
from pathlib import Path, PurePosixPath
import pickle

import pandas as pd
import numpy as np
import torch
from sklearn.preprocessing import OneHotEncoder

from DeepPurpose import utils
from DeepPurpose import DTI as models
from DeepPurpose.utils import *
from DeepPurpose.dataset import *

# read drug SMILES data
compound_smiles = pd.read_csv('./drugbank_smiles.txt', header=None, sep='\t')

# load model and set encodings
model_name = 'CNN_CNN_BindingDB'
net = models.model_pretrained(model=model_name)
drug_encoding = model_name.split('_')[0]
target_encoding = model_name.split('_')[1]

# preprocess SMILES
drug_l = compound_smiles[1].values
y_l = [-1]*len(X_drug)
X_drug = data_process(X_drug=drug_l, y=y_l,
                      drug_encoding=drug_encoding, target_encoding=target_encoding,
                      split_method='no_split')

# generate embeddings
with torch.no_grad():
    embs = utils.obtain_compound_embedding(net, X_drug)
    embs = embs.numpy()
```

**Comment by kexinhuang12345** [comment] 2020-11-03 03:35
I am able to fix the CNN/CNN_RNN error, please see the most up to date commit. The transformer and MPNN requires more sophisticated fix. I am pretty busy these two weeks, but i add this in the backlog and I will get back to you to fix this in a couple of weeks. meantime, feel free to try out and make a PR. Basically, MPNN and transformer has customized data loader collate functions.

**Comment by cynricfu** [comment] 2020-11-03 14:34
When using the following code to load the pretrained model `Morgan_CNN_KIBA`, it would trigger an error like below. And the downloaded zip file is named as `model_morgan_aac_kiba.zip`.

```python
# load model and set encodings
model_name = 'Morgan_CNN_KIBA'
net = models.model_pretrained(model=model_name)
drug_encoding = model_name.split('_')[0]
target_encoding = model_name.split('_')[1]
```
```
Downloading finished... Beginning to extract zip file...
pretrained model Successfully Downloaded...
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-123-b293e0948ba3> in <module>()
      1 # load model and set encodings
      2 model_name = 'Morgan_CNN_KIBA'
----> 3 net = models.model_pretrained(model=model_name)
      4 drug_encoding = model_name.split('_')[0]
      5 target_encoding = model_name.split('_')[1]

D:\mydir\GitHub\DeepPurpose\DeepPurpose\DTI.py in model_pretrained(path_dir, model)
     63         if model is not None:
     64                 path_dir = download_pretrained_model(model)
---> 65         config = load_dict(path_dir)
     66         model = DBTA(**config)
     67         model.load_pretrained(path_dir + '/model.pt')

D:\mydir\GitHub\DeepPurpose\DeepPurpose\utils.py in load_dict(path)
    941 
    942 def load_dict(path):
--> 943         with open(path + '/config.pkl', 'rb') as f:
    944                 return pickle.load(f)
    945 

FileNotFoundError: [Errno 2] No such file or directory: './save_folder\\pretrained_model\\model_morgan_aac_kiba/config.pkl'
```

**Comment by pykao** [comment] 2020-12-14 02:29
It looks like a path issue. Which os are you using? Windows?

**Comment by kexinhuang12345** [comment] 2020-12-27 01:09
Yes, it seems a path issue, I just created a pull request to fix it. Could you try now?

**Comment by kexinhuang12345** [comment] 2020-12-30 16:23
closing for now, feel free to reopen!

**Closed by kexinhuang12345** 2020-12-30 16:23 UTC
