### ISSUE TITLE
Is it possible to enter multiple SMILES and one single FASTA and perform a drug-target interaction prediction?

### ISSUE THREAD

**Issue by SteventheExorcist** [kexinhuang12345/DeepPurpose#89] opened 2021-02-07 07:22 UTC

**Comment by SteventheExorcist** [comment] 2021-02-07 07:25
I am currently creating new SMILES vectors using ChemGAN. According to the tutorial about DTI, I need to give a affinity score. What is that? Can I use my own database without KIBA or DAVIS?

**Comment by kexinhuang12345** [comment] 2021-02-07 17:36
Hi, do you want to make a prediction or want to train a model? Yeah, affinity score is basically the bindingness of drug-target. You can use any dataset you want.

**Comment by SteventheExorcist** [comment] 2021-02-08 03:32
I want to make a prediction using a trained model. I simply don't have the affinity score. Is it necessary? Thanks a lot for your time.

**Comment by SteventheExorcist** [comment] 2021-02-08 09:50
FYI: Currently, all the data I have is a bunch of SMILES molecules and a single FASTA.

**Comment by kexinhuang12345** [comment] 2021-02-08 17:17
Yeah, affinity score is like the label. So to train a new model, you have to have a label for this task. In your use case, I think you can use a pretrained model. Here is an example: https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/case-study-I-Drug-Repurposing-for-3CLPro.ipynb

Note that it is recommended to train a new model for a specific target of interest if you have some affinity scores data, because it is likely that the pretraining dataset may not contain similar target as yours, leading to bad generalizability.

**Comment by SteventheExorcist** [comment] 2021-02-09 10:27
Sorry for kept bothering you. How to input my own data in https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/case-study-I-Drug-Repurposing-for-3CLPro.ipynb

Quite frankly, I can't find a way to input my own data. Once again, thank you a lot for your help.

**Comment by SteventheExorcist** [comment] 2021-02-10 14:26
BTW, I think there is a bug in the "dataset.read_file_repurposing_library" command. When I attempt to input my own SMILES.txt, it gives "UnboundLocalError: local variable 'file' referenced before assignment." Thanks.

**Comment by kexinhuang12345** [comment] 2021-02-10 16:37
Hi, yeah, here is a tutorial on the data processing: https://github.com/kexinhuang12345/DeepPurpose/blob/master/DEMO/load_data_tutorial.ipynb

This should help you know the format of each function input and output.

**Comment by SteventheExorcist** [comment] 2021-02-11 09:31
Thanks a lot for your help! I really appreciate them. The codes are working now. Is the binding score a probability? Since I do not have enough data to test, I was wondering if you would know that. Thanks! Your advice are really helpful.

**Comment by kexinhuang12345** [comment] 2021-02-12 06:06
In binary case, yes, it is a probability. In regression, the score is the true binding score in various kinds of units, depending on the training dataset. In the notebook, it is nM. But again, the result is using pretrained model, the generalizability is not guaranteed.

**Comment by SteventheExorcist** [comment] 2021-02-12 06:35
Thank you! Without your help, I would not be able to run the code!

**Comment by kexinhuang12345** [comment] 2021-02-12 17:44
No problem! Closing for now

**Closed by kexinhuang12345** 2021-02-12 17:44 UTC

**Comment by SteventheExorcist** [comment] 2021-02-18 09:12
Hello. When I am running the code, I have to re-train the model every time. Do you have a pre-trained model so that I can just load it? Also, what exactly is the virtual screening function? Sorry to bother you again.

**Comment by kexinhuang12345** [comment] 2021-02-20 00:39
Hi, you can load any model by saving and loading it. Checkout cell 15,16 in https://github.com/kexinhuang12345/DeepPurpose/blob/master/Tutorial_1_DTI_Prediction.ipynb. Virtual screening is to predict based on many drug-target pairs.

**Comment by SteventheExorcist** [comment] 2021-02-20 13:57
Thanks. Which model do you recommend? I am trying to do a prediction between COVID-19 RNA polymerase and drug about COVID-19 (e.g. Remdesivir).

**Comment by SteventheExorcist** [comment] 2021-02-25 14:21
I was trying to run the PPI model. What are the requirements? Thanks a lot.
